// Simplified lot inventory interface that matches what we actually use
export interface SimplifiedLotInventory {
  lot_inventory_id: string;
  builder_id: string;
  region_id: string;
  community_id: string;
  community_phase_id: string | null;
  lot_status: string;
  lot: string;
  block: string | null;
  job_number: string | null;
  legal_plan: string | null;
  lot_info_tooltip: string | null;
  address1: string | null;
  address2: string | null;
  city: string | null;
  state: string | null;
  zip: string | null;
  legal_address: string | null;
  county: string | null;
  country: string | null;
  tract: string | null;
  floor_plan_id: string | null;
  garage_orientation: string | null;
  purchased_from: string | null;
  purchase_price: number | null;
  is_available_for_sale: boolean;
  construction_stage: number;
  lot_selling_price: number | null;
  selling_adjustment: number | null;
  direction_facing: string | null;
  building_floor: string | null;
  unit_number: string | null;
  legal_unit: string | null;
  monthly_hoa_fees: number | null;
  annual_hoa_fees: number | null;
  hoa_id: string | null;
  comments: string | null;
  lot_type: string | null;
  // Simplified alias fields
  lot_address: string | null;
  lot_city: string | null;
  lot_state: string | null;
  lot_zip: string | null;
  section: string | null;
  lot_size: number | null;
  lot_cost: number | null;
  lot_price: number | null;
  lot_premium: number | null;
  hoa_fee: number | null;
  tax_rate: number | null;
  school_district: string | null;
  notes: string | null;
  created_by: string;
  modified_by: string;
  created_at: Date;
  updated_at: Date;
}

export type CreateSimplifiedLotInventory = {
  builder_id: string;
  region_id: string;
  community_id: string;
  community_phase_id: string | null;
  lot: string;
  job_number: string | null;
  legal_plan: string | null;
  section: string | null;
  block: string | null;
  lot_address: string | null;
  lot_city: string | null;
  lot_state: string | null;
  lot_zip: string | null;
  lot_size: number | null;
  lot_type: string | null;
  lot_status: string;
  lot_cost: number | null;
  lot_price: number | null;
  lot_premium: number | null;
  hoa_fee: number | null;
  tax_rate: number | null;
  school_district: string | null;
  notes: string | null;
  created_by: string;
  modified_by: string;
};