export enum AddQuoteState {
  CHECKING_FOR_PRE_SELECTED_OPPORTUNITY = 'CHECKING_FOR_PRE_SELECTED_OPPORTUNITY',
  CHECKING_FOR_PRE_SELECTED_OPPORTUNITY_ERROR = 'CHECKING_FOR_PRE_SELECTED_OPPORTUNITY_ERROR',

  OPPORTUNITY_LOADING = 'OPPORTUNITY_LOADING',
  OPPORTUNITY_READY = 'OPPORTUNITY_READY',
  OPPORTUNITY_SELECTED = 'OPPORTUNITY_SELECTED',
  OPPORTUNITY_ERROR = 'OPPORTUNITY_ERROR',

  COMMUNITY_LOADING = 'COMMUNITY_LOADING',
  COMMUNITY_READY = 'COMMUNITY_READY',
  COMMUNITY_SELECTED = 'COMMUNITY_SELECTED',
  COMMUNITY_ERROR = 'COMMUNITY_ERROR',

  LOT_LOADING = 'LOT_LOADING',
  LOT_READY = 'LOT_READY',
  LOT_SELECTED = 'LOT_SELECTED',
  LOT_ERROR = 'LOT_ERROR',

  HOME_LOADING = 'HOME_LOADING',
  HOME_READY = 'HOME_READY',
  HOME_SELECTED = 'HOME_SELECTED',
  HOME_DETAILS_READY = 'HOME_DETAILS_READY',
  HOME_DETAILS_ERROR = 'HOME_DETAILS_ERROR',
  HOME_ERROR = 'HOME_ERROR',

  SELECT_HOME = 'SELECT_HOME',
  STRUCTURAL_OPTIONS_LOADING = 'STRUCTURAL_OPTIONS_LOADING',
  STRUCTURAL_OPTIONS_READY = 'STRUCTURAL_OPTIONS_READY',
  STRUCTURAL_OPTIONS_SELECTED = 'STRUCTURAL_OPTIONS_SELECTED',
  STRUCTURAL_OPTIONS_ERROR = 'STRUCTURAL_OPTIONS_ERROR',

  INTERIOR_EXTERIOR_LOADING = 'INTERIOR_EXTERIOR_LOADING',
  INTERIOR_EXTERIOR_READY = 'INTERIOR_EXTERIOR_READY',
  INTERIOR_EXTERIOR_SELECTED = 'INTERIOR_EXTERIOR_SELECTED',
  INTERIOR_EXTERIOR_ERROR = 'INTERIOR_EXTERIOR_ERROR',

  DEPOSIT_DETAILS_LOADING = 'DEPOSIT_DETAILS_LOADING',
  DEPOSIT_DETAILS_READY = 'DEPOSIT_DETAILS_READY',
  DEPOSIT_DETAILS_ERROR = 'DEPOSIT_DETAILS_ERROR',

  FINANCING_DETAILS_LOADING = 'FINANCING_DETAILS_LOADING',
  FINANCING_DETAILS_READY = 'FINANCING_DETAILS_READY',
  FINANCING_DETAILS_ERROR = 'FINANCING_DETAILS_ERROR',
}

export enum AddQuoteEvents {
  OPPORTUNITY_SELECTED = 'OPPORTUNITY_SELECTED',
  OPPORTUNITY_READY = 'OPPORTUNITY_READY',
  COMMUNITY_SELECTED = 'COMMUNITY_SELECTED',
  COMMUNITY_AND_PHASE_SELECTED = 'COMMUNITY_AND_PHASE_SELECTED',
  COMMUNITY_READY = 'COMMUNITY_READY',
  LOT_SELECTED = 'LOT_SELECTED',
  SELECT_HOME = 'SELECT_HOME',
  HOME_READY = 'HOME_READY',
  LOT_READY = 'LOT_READY',
  HOME_SELECTED = 'HOME_SELECTED',
  STRUCTURAL_OPTIONS_SELECTED = 'STRUCTURAL_OPTIONS_SELECTED',
  STRUCTURAL_OPTIONS_READY = 'STRUCTURAL_OPTIONS_READY',
  INTERIOR_EXTERIOR_READY = 'INTERIOR_EXTERIOR_READY',
  INTERIOR_EXTERIOR_SELECTED = 'INTERIOR_EXTERIOR_SELECTED',
  DEPOSIT_DETAILS_LOADED = 'DEPOSIT_DETAILS_LOADED',
  DEPOSIT_DETAILS_NEXT = 'DEPOSIT_DETAILS_NEXT',
  FINANCING_DETAILS_LOADED = 'FINANCING_DETAILS_LOADED',
}

